import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { NavLink, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import MainLayout from '../components/Layout/MainLayout';
import Loading from '../components/Loading';
import Summary from '../components/Summary';
import CustomChart from '../components/CustomChart';
import Balances from '../components/Balances';
import ExpenseForm from '../components/ExpenseForm';
import SettlementsPanel from '../components/SettlementsPanel';
import MembersPanel from '../components/MembersPanel';
import ActivityPanel from '../components/ActivityPanel';
import TripSettings from '../components/TripSettings';
import GovernancePanel from '../components/GovernancePanel';
import QuickExpense from '../components/QuickExpense';
import CategoryManager from '../components/CategoryManager';
import MemberDetail from '../components/MemberDetail';
import FundPanel from '../components/FundPanel';
import { addExpense, addSettlement, archiveCategory, archiveTrip, banMember, cancelFundingRound, closeFund, closeTrip, completeFundingRound, correctFundContribution, createCategory, createFund, createFundingRound, createInvitation, deleteExpense, deleteSettlement, getActivity, getBalances, getBans, getCategories, getCategoryBudgets, getExpenses, getFund, getInvitations, getJoinRequests, getMemberDetail, getMembers, getPage, getSettlements, getTrip, getTripSummary, kickMember, leaveTrip, previewFundRefund, recordFundContribution, recordFundRefunds, removeMember, reopenTrip, resendInvitation, resetCategoryBudget, restoreTrip, reviewJoinRequest, reviewSettlement, revokeBan, revokeInvitation, setCategoryBudget, transferOwnership, updateCategory, updateExpense, updateFund, updateMember, updateSettlement, updateTrip, voidFundContribution } from '../api';
import { permissionsFor } from '../utils/permissions';

const TripDetailsPage = () => {
  const { code: tripId } = useParams();
  const section = useParams()['*'] || 'overview';
  const navigate = useNavigate();
  const { t } = useTranslation();
  const [trip, setTrip] = useState(null), [members, setMembers] = useState([]), [expenses, setExpenses] = useState([]);
  const [budgets, setBudgets] = useState([]), [budgetSummary, setBudgetSummary] = useState(null), [balances, setBalances] = useState(null), [settlements, setSettlements] = useState([]), [activity, setActivity] = useState([]);
  const [pages, setPages] = useState({ expenses: null, settlements: null, activity: null });
  const [governance, setGovernance] = useState({ requests: [], invitations: [], bans: [] }), [categories, setCategories] = useState([]), [summary, setSummary] = useState(null);
  const [fund, setFund] = useState(null);
  const [sectionErrors, setSectionErrors] = useState({});
  const [editing, setEditing] = useState(null), [showFullExpense, setShowFullExpense] = useState(false), [memberDetail, setMemberDetail] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = useCallback(async () => {
    const tripData = await getTrip(tripId);
    setTrip(tripData);
    const resources = { members: getMembers(tripId) };
    if (section === 'overview') Object.assign(resources, { summary: getTripSummary(tripId), balances: getBalances(tripId), fund: getFund(tripId) });
    if (section === 'expenses') Object.assign(resources, { expenses: getExpenses(tripId), categories: getCategories(tripId), fund: getFund(tripId) });
    if (section === 'balances') Object.assign(resources, { balances: getBalances(tripId), settlements: getSettlements(tripId) });
    if (section === 'fund') Object.assign(resources, { fund: getFund(tripId) });
    if (section === 'categories') Object.assign(resources, { categories: getCategories(tripId), budgets: getCategoryBudgets(tripId) });
    if (section === 'settlements') Object.assign(resources, { balances: getBalances(tripId), settlements: getSettlements(tripId) });
    if (section === 'activity') Object.assign(resources, { activity: getActivity(tripId) });
    const keys = Object.keys(resources), results = await Promise.allSettled(Object.values(resources));
    const values = {}, failures = {};
    results.forEach((result, index) => { if (result.status === 'fulfilled') values[keys[index]] = result.value; else failures[keys[index]] = result.reason?.message || t('error.action'); });
    if (values.members) setMembers(values.members.results); if (values.expenses) setExpenses(values.expenses.results); if (values.budgets) { setBudgets(values.budgets.results); setBudgetSummary(values.budgets.summary); } if (values.balances) setBalances(values.balances); if (values.settlements) setSettlements(values.settlements.results); if (values.activity) setActivity(values.activity.results); if (values.categories) setCategories(values.categories.results); if (values.summary) setSummary(values.summary); if (values.fund !== undefined) setFund(values.fund);
    setPages((current) => ({ expenses: values.expenses?.next ?? current.expenses, settlements: values.settlements?.next ?? current.settlements, activity: values.activity?.next ?? current.activity })); setSectionErrors(failures);
    if (section === 'members' && ['owner', 'admin'].includes(tripData.current_member?.role)) { const governanceResults = await Promise.allSettled([getJoinRequests(tripId), getInvitations(tripId), getBans(tripId)]); if (governanceResults.every((item) => item.status === 'fulfilled')) setGovernance({ requests: governanceResults[0].value.results, invitations: governanceResults[1].value.results, bans: governanceResults[2].value.results }); else setSectionErrors((current) => ({ ...current, governance: t('error.action') })); }
  }, [tripId, section, t]);
  useEffect(() => { setLoading(true); load().catch((err) => setError(err.message || t('error.loadTrip'))).finally(() => setLoading(false)); }, [load, t]);
  const currentMember = trip?.current_member;
  const permissions = useMemo(() => permissionsFor(currentMember, Boolean(trip?.archived_at), trip?.lifecycle_status === 'closed'), [currentMember, trip?.archived_at, trip?.lifecycle_status]);
  const refreshFinancials = async () => { const [expenseData, balanceData, settlementData, activityData] = await Promise.all([getExpenses(tripId), getBalances(tripId), getSettlements(tripId), getActivity(tripId)]); setExpenses(expenseData.results); setBalances(balanceData); setSettlements(settlementData.results); setActivity(activityData.results); };
  const loadMore = (kind, setter) => guard(async () => { const result = await getPage(pages[kind], tripId); setter((rows) => [...rows, ...result.results.filter((row) => !rows.some((old) => old.id === row.id))]); setPages((current) => ({ ...current, [kind]: result.next })); });
  const guard = async (action) => { setError(''); try { await action(); } catch (err) { setError(err.message || t('error.action')); } };
  const saveExpense = (payload) => guard(async () => { if (editing && !editing.duplicate) await updateExpense(tripId, editing.id, payload); else await addExpense(tripId, { ...payload, idempotency_key: crypto.randomUUID() }); setEditing(null); await refreshFinancials(); });
  const memberName = (id) => members.find((m) => m.id === id)?.display_name || t('activity.unknown');
  if (loading) return <Loading />;
  if (!trip) return <MainLayout><div className="error-message">{error}<button onClick={() => navigate('/')}>{t('Home')}</button></div></MainLayout>;
  return <MainLayout><main className="home-container-pc mt-5">
    <section className="card-pc trip-details-card"><h2>{trip.title}</h2><p>{t('trip.budget')}: {trip.budget} {trip.currency}</p><p>{t('trip.code')}: <strong>{trip.join_code}</strong></p><p>{t(`role.${currentMember?.role}`)}</p><button className="pc-btn-refresh" onClick={() => guard(load)}>{t('refresh.button.text')}</button></section>
    {trip.archived_at && <div className="archive-banner" role="status">{t('trip.archivedReadOnly')}</div>}
    {error && <div className="error-message" role="alert">{error}</div>}
    {Object.keys(sectionErrors).length > 0 && <div className="error-message" role="alert"><strong>{t('error.partialLoad')}</strong><p>{Object.keys(sectionErrors).join(', ')}</p><button type="button" onClick={() => guard(load)}>{t('refresh.button.text')}</button></div>}
    <nav className="trip-section-nav" aria-label={t('trip.sections')}>{[['overview','trip.overview'],['expenses','expense.history'],['balances','balances.title'],['fund','fund.title'],['members','members.title'],['categories','categories.title'],['settlements','settlements.history'],['activity','activity.title'],['settings','settings.title']].map(([id, label]) => <NavLink key={id} className={({isActive})=>isActive?'active':''} to={`/trips/${tripId}/${id}`}>{t(label)}</NavLink>)}</nav>
    {section === 'overview' && <section id="overview" className="card-pc"><Summary budget={trip.budget} expenses={[]} currency={trip.currency} />{summary && <div className="summary-grid"><p>{t('dashboard.shared')}: {summary.shared_spending} {trip.currency}</p><p>{t('dashboard.personal')}: {summary.personal_spending} {trip.currency}</p><p>{t('dashboard.yourBalance')}: {summary.current_member?.balance} {trip.currency}</p>{fund && <p>{t('fund.available')}: {fund.accounting.balance} {trip.currency}</p>}</div>}</section>}
    {section === 'fund' && <FundPanel fund={fund} members={members} currentMember={currentMember} currency={trip.currency} disabled={!permissions.canManageMembers} onCreate={(payload) => guard(async () => { await createFund(tripId, payload); await load(); })} onUpdate={(payload) => guard(async () => { await updateFund(tripId, payload); await load(); })} onRound={(payload) => guard(async () => { await createFundingRound(tripId, payload); await load(); })} onContribution={(roundId, payload) => guard(async () => { await recordFundContribution(tripId, roundId, payload); await load(); })} onCorrectContribution={(row, payload) => guard(async () => { await correctFundContribution(tripId, row.round_id, row.id, payload); await load(); })} onVoidContribution={(row, reason) => guard(async () => { await voidFundContribution(tripId, row.round_id, row.id, { reason }); await load(); })} onCompleteRound={(row, shortfall) => guard(async () => { if (!shortfall || window.confirm(t('fund.partialCompleteWarning', { amount: shortfall, currency: trip.currency }))) { await completeFundingRound(tripId, row.id); await load(); } })} onCancelRound={(row) => guard(async () => { if (window.confirm(t('fund.cancelWarning'))) { await cancelFundingRound(tripId, row.id); await load(); } })} onPreviewRefund={(payload) => previewFundRefund(tripId, payload)} onRefund={(payload) => guard(async () => { await recordFundRefunds(tripId, payload); await load(); })} onClose={() => guard(async () => { await closeFund(tripId); await load(); })} />}
    {(section === 'balances' || section === 'settlements') && <Balances data={balances} />}
    {section === 'settlements' && <><SettlementsPanel members={members} currency={trip.currency} settlements={settlements} suggestion={balances?.suggested_settlements?.[0]} currentMember={currentMember} pendingCount={trip.pending_settlement_confirmations} disabled={!permissions.canRecordSettlement} onSave={(payload, settlementId) => guard(async () => { if (settlementId) await updateSettlement(tripId, settlementId, payload); else await addSettlement(tripId, payload); await load(); })} onDelete={(row) => guard(async () => { if (window.confirm(t('settlements.confirmDelete'))) { await deleteSettlement(tripId, row.id); await load(); } })} onReview={(row, decision) => guard(async () => { await reviewSettlement(tripId, row.id, decision); await load(); })} />{pages.settlements && <button onClick={() => loadMore('settlements', setSettlements)}>{t('common.loadMore')}</button>}</>}
    {section === 'categories' && <CategoryManager categories={categories} budgets={budgets} budgetSummary={budgetSummary} currency={trip.currency} canManage={permissions.canManageMembers} onCreate={(payload) => guard(async () => { await createCategory(tripId, payload); await load(); })} onUpdate={(category, payload) => guard(async () => { await updateCategory(tripId, category.id, payload); await load(); })} onArchive={(category) => guard(async () => { if (window.confirm(t('categories.archiveWarning'))) { await archiveCategory(tripId, category.id); await load(); } })} onBudget={(category, budget) => guard(async () => { await setCategoryBudget(tripId, { category: category.code, budget, currency: trip.currency }); await load(); })} onResetBudget={(category) => guard(async () => { await resetCategoryBudget(tripId, category.id); await load(); })} />}
    {section === 'expenses' && <>{permissions.canCreateExpense && <section id="expenses" className="card-pc"><h2>{editing ? t('expense.edit') : t('quick.title')}</h2>{!editing && !showFullExpense ? <QuickExpense currentMember={currentMember} members={members} categories={categories} onSubmit={saveExpense} onMore={() => setShowFullExpense(true)} /> : <ExpenseForm key={editing?.id || 'create'} members={members} categories={categories} currentMember={currentMember} tripCurrency={trip.currency} hasFund={Boolean(fund && fund.status === 'active')} expense={editing} onSubmit={saveExpense} onCancel={() => { setEditing(null); setShowFullExpense(false); }} />}</section>}<section className="card-pc"><h2>{t('expense.history')}</h2>{expenses.length ? <div className="expenses-list">{expenses.map((expense) => <article className="expense-item" key={expense.id}><div><h4>{expense.title}</h4><p>{t(`category.${expense.category}`, { defaultValue: expense.category })} · {expense.expense_date} · {t(`expense.scope.${expense.scope}`)}</p><p>{expense.original_currency !== trip.currency ? <>{expense.original_amount} {expense.original_currency} ≈ {expense.amount} {trip.currency}</> : <>{expense.amount} {trip.currency}</>}</p><p>{expense.payment_source === 'trip_fund' ? t('fund.paidFromFund') : `${t('expense.paidBy')}: ${expense.payments.map((row) => `${memberName(row.member_id)} ${row.amount}`).join(' + ')}`}</p></div><div className="row-actions"><button onClick={() => setEditing({ ...expense, duplicate: true, expense_date: new Date().toISOString().slice(0, 10) })}>{t('expense.duplicate')}</button>{permissions.canEditExpense(expense) && <><button onClick={() => setEditing(expense)}>{t('common.edit')}</button><button onClick={() => guard(async () => { if (window.confirm(t('expense.confirmDelete'))) { await deleteExpense(tripId, expense.id); await refreshFinancials(); } })}>{t('common.delete')}</button></>}</div></article>)}</div> : <p>{t('expense.empty')}</p>}{pages.expenses && <button onClick={() => loadMore('expenses', setExpenses)}>{t('common.loadMore')}</button>}</section><section className="card-pc"><CustomChart expenses={expenses} /></section></>}
    {section === 'members' && <><MembersPanel members={members} currentMember={currentMember} permissions={permissions} onDetails={(member) => guard(async () => setMemberDetail(await getMemberDetail(tripId, member.id)))} onRole={(member, role) => guard(async () => { await updateMember(tripId, member.id, { role }); await load(); })} onRemove={(member) => guard(async () => { if (window.confirm(t('members.confirmRemove'))) { await removeMember(tripId, member.id); await load(); } })} onTransfer={(member) => guard(async () => { if (window.confirm(t('members.confirmTransfer'))) { await transferOwnership(tripId, member.id); await load(); } })} onLeave={() => guard(async () => { if (window.confirm(t('members.confirmLeave'))) { await leaveTrip(tripId); navigate('/'); } })} /><MemberDetail detail={memberDetail} currency={trip.currency} onClose={() => setMemberDetail(null)} />{permissions.canManageMembers && <GovernancePanel {...governance} members={members} onReview={(row, decision) => guard(async () => { await reviewJoinRequest(tripId, row.id, decision); await load(); })} onInvite={(payload) => createInvitation(tripId, payload).then((result) => { load(); return result; })} onResendInvite={(row) => guard(async () => { const result = await resendInvitation(tripId, row.id); if (result.token) window.prompt(t('governance.copyOnce'), `${window.location.origin}/invite/${result.token}`); await load(); })} onRevokeInvite={(row) => guard(async () => { await revokeInvitation(tripId, row.id); await load(); })} onKick={(member) => guard(async () => { await kickMember(tripId, member.id); await load(); })} onBan={(member, duration) => guard(async () => { await banMember(tripId, member.id, { duration }); await load(); })} onUnban={(ban) => guard(async () => { await revokeBan(tripId, ban.id); await load(); })} />}</>}
    {section === 'settings' && <><TripSettings trip={trip} permissions={permissions} onUpdate={(payload) => guard(async () => { const updated = await updateTrip(tripId, payload); setTrip({ ...trip, ...updated, current_member: currentMember }); })} onArchive={() => guard(async () => { if (window.confirm(t('trip.confirmArchive'))) { await archiveTrip(tripId); setTrip({ ...trip, archived_at: new Date().toISOString() }); } })} onRestore={() => guard(async () => { const restored = await restoreTrip(tripId); setTrip({ ...trip, ...restored, current_member: currentMember }); })} />{permissions.canArchiveTrip && <section className="card-pc"><button onClick={() => guard(async () => { const updated = trip.lifecycle_status === 'closed' ? await reopenTrip(tripId) : await closeTrip(tripId); setTrip({ ...trip, ...updated, current_member: currentMember }); })}>{t(trip.lifecycle_status === 'closed' ? 'trip.reopen' : 'trip.close')}</button></section>}</>}
    {section === 'activity' && <><ActivityPanel events={activity} />{pages.activity && <button onClick={() => loadMore('activity', setActivity)}>{t('common.loadMore')}</button>}</>}
  </main></MainLayout>;
};
export default TripDetailsPage;
