import React, { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { avatarGlyph } from '../utils/avatars';

const today = () => new Date().toISOString().slice(0, 10);

const FundPanel = ({ fund, members, currentMember, currency, disabled, onCreate, onUpdate, onRound, onContribution, onPreviewRefund, onRefund, onClose }) => {
  const { t } = useTranslation();
  const canManage = !disabled && ['owner', 'admin'].includes(currentMember?.role);
  const [round, setRound] = useState({ title: '', target_amount: '', contribution_method: 'equal', participant_ids: members.filter((m) => m.active !== false).map((m) => m.id), custom: {} });
  const [contribution, setContribution] = useState({ round_id: '', member_id: '', amount: '', contribution_date: today(), note: '' });
  const [refundMethod, setRefundMethod] = useState('proportional_to_contributions');
  const [preview, setPreview] = useState([]);
  const deficit = Number(fund?.accounting?.deficit || 0);
  const activeMembers = useMemo(() => members.filter((member) => member.active !== false), [members]);
  if (!fund) return <section id="fund" className="card-pc"><h2>{t('fund.title')}</h2><p>{t('fund.empty')}</p>{canManage && <button className="pc-btn-create" onClick={() => onCreate({ name: t('fund.title'), holder_id: currentMember.id })}>{t('fund.create')}</button>}</section>;
  const submitRound = (event) => { event.preventDefault(); const payload = { title: round.title, target_amount: round.target_amount, contribution_method: round.contribution_method, participant_ids: round.participant_ids }; if (round.contribution_method === 'custom') payload.custom_expectations = round.participant_ids.map((member_id) => ({ member_id, amount: round.custom[member_id] || '' })); onRound(payload); };
  const accounting = fund.accounting;
  return <section id="fund" className="card-pc fund-panel"><header className="fund-header"><div><h2>{fund.name}</h2><p>{t('fund.holder')}: {avatarGlyph(fund.holder.avatar_key)} {fund.holder.display_name}</p></div>{canManage && <select aria-label={t('fund.changeHolder')} className="pc-input compact-input" value={fund.holder.id} onChange={(event) => onUpdate({ holder_id: event.target.value })}>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select>}</header>
    <div className="fund-metrics"><div><span>{t('fund.collected')}</span><strong>{accounting.collected} {currency}</strong></div><div><span>{t('fund.spent')}</span><strong>{accounting.spent} {currency}</strong></div><div><span>{deficit ? t('fund.deficit') : t('fund.available')}</span><strong>{deficit ? accounting.deficit : accounting.balance} {currency}</strong></div></div>
    {deficit > 0 && canManage && <button type="button" onClick={() => setRound({ ...round, title: t('fund.topup'), target_amount: accounting.deficit })}>{t('fund.createTopup')}</button>}
    {fund.rounds.map((item) => <article className="fund-round" key={item.id}><h3>#{item.sequence_number} {item.title}</h3><p>{item.statistics.collected} / {item.statistics.target} {currency} · {item.statistics.percentage_collected}%</p><progress max="100" value={Math.min(Number(item.statistics.percentage_collected), 100)} />{item.statistics.members.map((row) => <div className="fund-member" key={row.member_id}><span>{avatarGlyph(row.avatar_key)} {row.display_name}</span><span>{t('fund.expected')} {row.expected} · {t('fund.paid')} {row.paid} · {t('fund.remaining')} {row.remaining}</span></div>)}</article>)}
    {canManage && <><form className="fund-form" onSubmit={submitRound}><h3>{t('fund.newRound')}</h3><label>{t('fund.roundTitle')}<input className="pc-input" value={round.title} onChange={(e) => setRound({ ...round, title: e.target.value })} required /></label><label>{t('fund.target')}<input className="pc-input" inputMode="decimal" type="number" min="0.01" step="0.01" value={round.target_amount} onChange={(e) => setRound({ ...round, target_amount: e.target.value })} required /></label><label>{t('fund.method')}<select className="pc-input" value={round.contribution_method} onChange={(e) => setRound({ ...round, contribution_method: e.target.value })}><option value="equal">{t('fund.equal')}</option><option value="custom">{t('fund.custom')}</option></select></label><fieldset><legend>{t('expense.participants')}</legend>{activeMembers.map((member) => <label className="fund-participant" key={member.id}><input type="checkbox" checked={round.participant_ids.includes(member.id)} onChange={() => setRound({ ...round, participant_ids: round.participant_ids.includes(member.id) ? round.participant_ids.filter((id) => id !== member.id) : [...round.participant_ids, member.id] })} /> {member.display_name}{round.contribution_method === 'custom' && round.participant_ids.includes(member.id) && <input aria-label={`${member.display_name} ${t('fund.expected')}`} inputMode="decimal" type="number" min="0" step="0.01" value={round.custom[member.id] || ''} onChange={(e) => setRound({ ...round, custom: { ...round.custom, [member.id]: e.target.value } })} />}</label>)}</fieldset><button className="pc-btn-create">{t('fund.createRound')}</button></form>
    <form className="fund-form" onSubmit={(event) => { event.preventDefault(); onContribution(contribution.round_id, { ...contribution, idempotency_key: crypto.randomUUID() }); }}><h3>{t('fund.recordContribution')}</h3><select aria-label={t('fund.round')} className="pc-input" value={contribution.round_id} onChange={(e) => setContribution({ ...contribution, round_id: e.target.value })} required><option value="">—</option>{fund.rounds.filter((item) => item.status === 'open').map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select aria-label={t('fund.member')} className="pc-input" value={contribution.member_id} onChange={(e) => setContribution({ ...contribution, member_id: e.target.value })} required><option value="">—</option>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select><input aria-label={t('fund.amount')} className="pc-input" inputMode="decimal" type="number" min="0.01" step="0.01" value={contribution.amount} onChange={(e) => setContribution({ ...contribution, amount: e.target.value })} required /><input aria-label={t('expense.date')} className="pc-input" type="date" value={contribution.contribution_date} onChange={(e) => setContribution({ ...contribution, contribution_date: e.target.value })} /><button>{t('fund.record')}</button></form>
    {Number(accounting.surplus) > 0 && <div className="fund-form"><h3>{t('fund.refund')}</h3><select className="pc-input" value={refundMethod} onChange={(e) => setRefundMethod(e.target.value)}><option value="proportional_to_contributions">{t('fund.proportional')}</option><option value="equal">{t('fund.equal')}</option></select><button onClick={async () => setPreview(await onPreviewRefund({ method: refundMethod, member_ids: activeMembers.map((m) => m.id) }))}>{t('fund.preview')}</button>{preview.map((row) => <p key={row.member_id}>{row.display_name}: {row.amount} {currency}</p>)}{preview.length > 0 && <button onClick={() => onRefund({ method: refundMethod, member_ids: activeMembers.map((m) => m.id), refund_date: today(), idempotency_key: crypto.randomUUID() })}>{t('fund.distribute')}</button>}</div>}
    {currentMember?.role === 'owner' && <button onClick={onClose}>{t('fund.close')}</button>}</>}
  </section>;
};

export default FundPanel;
