import React, { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { avatarGlyph } from '../utils/avatars';

const today = () => new Date().toISOString().slice(0, 10);

const FundPanel = ({ fund, members, currentMember, currency, disabled, onCreate, onUpdate, onRound, onContribution, onCorrectContribution, onVoidContribution, onCompleteRound, onCancelRound, onPreviewRefund, onRefund, onClose }) => {
  const { t } = useTranslation();
  const canManage = !disabled && ['owner', 'admin'].includes(currentMember?.role);
  const [round, setRound] = useState({ title: '', target_amount: '', contribution_method: 'equal', participant_ids: members.filter((m) => m.active !== false).map((m) => m.id), custom: {} });
  const [contribution, setContribution] = useState({ round_id: '', member_id: '', amount: '', contribution_date: today(), note: '' });
  const [refund, setRefund] = useState({ method: 'proportional_to_net_contributions', distribution_amount: '', custom: {} });
  const [preview, setPreview] = useState(null);
  const [correction, setCorrection] = useState(null);
  const deficit = Number(fund?.accounting?.deficit || 0);
  const activeMembers = useMemo(() => members.filter((member) => member.active !== false), [members]);
  if (!fund) return <section id="fund" className="card-pc"><h2>{t('fund.title')}</h2><p>{t('fund.empty')}</p>{canManage && <button className="pc-btn-create" onClick={() => onCreate({ name: t('fund.title'), holder_id: currentMember.id })}>{t('fund.create')}</button>}</section>;
  const submitRound = (event) => { event.preventDefault(); const payload = { title: round.title, target_amount: round.target_amount, contribution_method: round.contribution_method, participant_ids: round.participant_ids }; if (round.contribution_method === 'custom') payload.custom_expectations = round.participant_ids.map((member_id) => ({ member_id, amount: round.custom[member_id] || '' })); onRound(payload); };
  const accounting = fund.accounting;
  return <section id="fund" className="card-pc fund-panel"><header className="fund-header"><div><h2>{fund.name}</h2><p>{t('fund.holder')}: {avatarGlyph(fund.holder.avatar_key)} {fund.holder.display_name}</p></div>{canManage && <select aria-label={t('fund.changeHolder')} className="pc-input compact-input" value={fund.holder.id} onChange={(event) => onUpdate({ holder_id: event.target.value })}>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select>}</header>
    <div className="fund-metrics"><div><span>{t('fund.collected')}</span><strong>{accounting.collected} {currency}</strong></div><div><span>{t('fund.spent')}</span><strong>{accounting.spent} {currency}</strong></div><div><span>{t('fund.refunded')}</span><strong>{accounting.refunded} {currency}</strong></div><div><span>{deficit ? t('fund.deficit') : t('fund.available')}</span><strong>{deficit ? accounting.deficit : accounting.balance} {currency}</strong></div></div>
    {deficit > 0 && canManage && <button type="button" onClick={() => setRound({ ...round, title: t('fund.topup'), target_amount: accounting.deficit })}>{t('fund.createTopup')}</button>}
    {fund.rounds.map((item) => <article className="fund-round" key={item.id}><header><h3>#{item.sequence_number} {item.title}</h3><strong>{t(`fund.status.${item.status}`)}</strong></header><p>{t('fund.target')} {item.statistics.target} · {t('fund.collected')} {item.statistics.collected} · {t('fund.remaining')} {item.statistics.remaining} {currency}</p><progress max="100" value={Math.min(Number(item.statistics.percentage_collected), 100)} />{item.statistics.members.map((row) => <div className="fund-member" key={row.member_id}><span>{avatarGlyph(row.avatar_key)} {row.display_name}</span><span>{t('fund.expected')} {row.expected} · {t('fund.paid')} {row.paid} · {t('fund.remaining')} {row.remaining}{Number(row.overpaid) > 0 ? ` · ${t('fund.overpaid')} ${row.overpaid}` : ''}</span></div>)}{canManage && item.status === 'open' && <div className="fund-actions"><button type="button" onClick={() => onCompleteRound(item, Number(item.statistics.remaining))}>{t('fund.completeRound')}</button><button type="button" disabled={Number(item.statistics.collected) > 0} onClick={() => onCancelRound(item)}>{t('fund.cancelRound')}</button></div>}</article>)}
    {canManage && fund.status === 'active' && <><form className="fund-form" onSubmit={submitRound}><h3>{t('fund.newRound')}</h3><label>{t('fund.roundTitle')}<input className="pc-input" value={round.title} onChange={(e) => setRound({ ...round, title: e.target.value })} required /></label><label>{t('fund.target')}<input className="pc-input" inputMode="decimal" type="number" min="0.01" step="0.01" value={round.target_amount} onChange={(e) => setRound({ ...round, target_amount: e.target.value })} required /></label><label>{t('fund.method')}<select className="pc-input" value={round.contribution_method} onChange={(e) => setRound({ ...round, contribution_method: e.target.value })}><option value="equal">{t('fund.equal')}</option><option value="custom">{t('fund.custom')}</option></select></label><fieldset><legend>{t('expense.participants')}</legend>{activeMembers.map((member) => <label className="fund-participant" key={member.id}><input type="checkbox" checked={round.participant_ids.includes(member.id)} onChange={() => setRound({ ...round, participant_ids: round.participant_ids.includes(member.id) ? round.participant_ids.filter((id) => id !== member.id) : [...round.participant_ids, member.id] })} /> {member.display_name}{round.contribution_method === 'custom' && round.participant_ids.includes(member.id) && <input aria-label={`${member.display_name} ${t('fund.expected')}`} inputMode="decimal" type="number" min="0" step="0.01" value={round.custom[member.id] || ''} onChange={(e) => setRound({ ...round, custom: { ...round.custom, [member.id]: e.target.value } })} />}</label>)}</fieldset><button className="pc-btn-create">{t('fund.createRound')}</button></form>
    <form className="fund-form" onSubmit={(event) => { event.preventDefault(); onContribution(contribution.round_id, { ...contribution, idempotency_key: crypto.randomUUID() }); }}><h3>{t('fund.recordContribution')}</h3><select aria-label={t('fund.round')} className="pc-input" value={contribution.round_id} onChange={(e) => setContribution({ ...contribution, round_id: e.target.value })} required><option value="">—</option>{fund.rounds.filter((item) => item.status === 'open').map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select aria-label={t('fund.member')} className="pc-input" value={contribution.member_id} onChange={(e) => setContribution({ ...contribution, member_id: e.target.value })} required><option value="">—</option>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select><input aria-label={t('fund.amount')} className="pc-input" inputMode="decimal" type="number" min="0.01" step="0.01" value={contribution.amount} onChange={(e) => setContribution({ ...contribution, amount: e.target.value })} required /><input aria-label={t('expense.date')} className="pc-input" type="date" value={contribution.contribution_date} onChange={(e) => setContribution({ ...contribution, contribution_date: e.target.value })} /><button>{t('fund.record')}</button></form></>}
    <section className="fund-section"><h3>{t('fund.contributionHistory')}</h3>{(fund.contributions || []).map((row) => <article className={`fund-history-row ${row.voided ? 'voided' : ''}`} key={row.id}><div><strong>{row.display_name}</strong><p>{row.amount} {currency} · {row.contribution_date} · {row.round_title}</p>{row.voided && <small>{t('fund.voided')}</small>}</div>{canManage && !row.voided && fund.status === 'active' && <div className="fund-actions"><button type="button" onClick={() => setCorrection({ ...row, corrected_amount: row.amount, reason: '' })}>{t('fund.correct')}</button><button type="button" onClick={() => { const reason = window.prompt(t('fund.correctionReason')); if (reason) onVoidContribution(row, reason); }}>{t('fund.void')}</button></div>}</article>)}</section>
    {correction && <div className="fund-correction" role="dialog" aria-modal="true"><h3>{t('fund.correctContribution')}</h3><p>{correction.display_name}: {correction.amount} {currency}</p><label>{t('fund.correctAmount')}<input inputMode="decimal" type="number" min="0.01" step="0.01" value={correction.corrected_amount} onChange={(e) => setCorrection({ ...correction, corrected_amount: e.target.value })} /></label><label>{t('fund.correctionReason')}<textarea value={correction.reason} onChange={(e) => setCorrection({ ...correction, reason: e.target.value })} /></label><div className="fund-actions"><button type="button" disabled={!correction.reason || !correction.corrected_amount} onClick={() => { onCorrectContribution(correction, { amount: correction.corrected_amount, reason: correction.reason }); setCorrection(null); }}>{t('common.save')}</button><button type="button" onClick={() => setCorrection(null)}>{t('common.cancel')}</button></div></div>}
    {Number(accounting.surplus) > 0 && <div className="fund-form"><h3>{t('fund.refund')}</h3><p>{t('fund.available')}: {accounting.surplus} {currency}</p><label>{t('fund.distributionAmount')}<input aria-label={t('fund.distributionAmount')} inputMode="decimal" type="number" min="0.01" max={accounting.surplus} step="0.01" value={refund.distribution_amount} placeholder={accounting.surplus} onChange={(e) => { setRefund({ ...refund, distribution_amount: e.target.value }); setPreview(null); }} /></label><select aria-label={t('fund.refundMethod')} className="pc-input" value={refund.method} onChange={(e) => { setRefund({ ...refund, method: e.target.value }); setPreview(null); }}><option value="proportional_to_net_contributions">{t('fund.proportional')}</option><option value="equal">{t('fund.equal')}</option><option value="custom">{t('fund.custom')}</option><option value="keep_in_fund">{t('fund.keep')}</option></select>{refund.method === 'custom' && fund.rounds.flatMap((item) => item.statistics.members).filter((row, index, all) => all.findIndex((other) => other.member_id === row.member_id) === index).map((row) => <label className="fund-custom-refund" key={row.member_id}>{row.display_name}<input aria-label={`${row.display_name} ${t('fund.refund')}`} inputMode="decimal" type="number" min="0" step="0.01" value={refund.custom[row.member_id] || ''} onChange={(e) => { setRefund({ ...refund, custom: { ...refund.custom, [row.member_id]: e.target.value } }); setPreview(null); }} /></label>)}{refund.method !== 'keep_in_fund' && <button type="button" onClick={async () => { const payload = { method: refund.method, distribution_amount: refund.distribution_amount || accounting.surplus }; if (refund.method === 'equal') payload.member_ids = fund.rounds.flatMap((item) => item.statistics.members.map((row) => row.member_id)).filter((id, index, all) => all.indexOf(id) === index); if (refund.method === 'custom') payload.custom = Object.entries(refund.custom).filter(([, amount]) => Number(amount) > 0).map(([member_id, amount]) => ({ member_id, amount })); setPreview(await onPreviewRefund(payload)); }}>{t('fund.preview')}</button>}{refund.method === 'keep_in_fund' && <p>{t('fund.keepExplanation')}</p>}{preview && <div className="refund-preview"><h4>{t('fund.refundPreview')}</h4>{preview.allocations.map((row) => <p key={row.member_id}>{row.display_name}: {row.refund_amount || row.amount} {currency}</p>)}<p>{t('fund.remainingAfterRefund')}: {preview.remaining_balance} {currency}</p><button type="button" onClick={() => onRefund({ method: refund.method, distribution_amount: preview.distribution_amount, custom: refund.method === 'custom' ? Object.entries(refund.custom).filter(([, amount]) => Number(amount) > 0).map(([member_id, amount]) => ({ member_id, amount })) : undefined, refund_date: today(), idempotency_key: crypto.randomUUID() })}>{t('fund.confirmRefund')}</button></div>}</div>}
    <section className="fund-section"><h3>{t('fund.refundHistory')}</h3>{(fund.refunds || []).length ? fund.refunds.map((row) => <article className="fund-history-row" key={row.id}><strong>{row.display_name}</strong><span>{row.amount} {currency} · {row.refund_date} · {t(`fund.refundMethods.${row.method}`)}</span></article>) : <p>{t('fund.noRefunds')}</p>}</section>
    {currentMember?.role === 'owner' && fund.status === 'active' && <button onClick={onClose}>{t('fund.close')}</button>}
  </section>;
};

export default FundPanel;
