import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

const SettlementsPanel = ({ members, currency, settlements, suggestion, currentMember, pendingCount = 0, onSave, onDelete, onReview, disabled }) => {
  const { t } = useTranslation();
  const [editing, setEditing] = useState(null);
  const blank = () => ({ from_member_id: suggestion?.from_member || currentMember?.id || '', to_member_id: suggestion?.to_member || '', amount: suggestion?.amount || '', settlement_date: new Date().toISOString().slice(0, 10), note: '' });
  const [form, setForm] = useState(blank);
  const submit = (event) => { event.preventDefault(); onSave({ ...form, currency, ...(editing ? {} : { idempotency_key: crypto.randomUUID() }) }, editing?.id); setEditing(null); setForm(blank()); };
  const edit = (row) => { setEditing(row); setForm({ from_member_id: row.from_member_id, to_member_id: row.to_member_id, amount: row.amount, settlement_date: row.settlement_date, note: row.note || '' }); };
  return <section className="card-pc">
    <h2>{t('settlements.title')} {pendingCount > 0 && <span className="status-badge">{pendingCount}</span>}</h2>
    {!disabled && <form onSubmit={submit}><label>{t('settlements.from')}<select className="pc-input" value={form.from_member_id} onChange={(event) => setForm({ ...form, from_member_id: event.target.value })}>{members.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label><label>{t('settlements.to')}<select className="pc-input" value={form.to_member_id} onChange={(event) => setForm({ ...form, to_member_id: event.target.value })}><option value="">—</option>{members.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label><label>{t('expense.amount')}<input className="pc-input" type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></label><label>{t('expense.date')}<input className="pc-input" type="date" value={form.settlement_date} onChange={(event) => setForm({ ...form, settlement_date: event.target.value })} /></label><label>{t('expense.notes')}<input className="pc-input" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label><div className="form-actions"><button className="pc-btn-create" disabled={!form.to_member_id || form.from_member_id === form.to_member_id}>{editing ? t('common.save') : t('settlements.record')}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(blank()); }}>{t('common.cancel')}</button>}</div></form>}
    <h3>{t('settlements.history')}</h3>{settlements.length ? settlements.map((row) => { const manageable = !disabled && (currentMember?.role !== 'member' || row.created_by === currentMember?.id); const canReview = row.status === 'pending' && (row.to_member_id === currentMember?.id || ['owner', 'admin'].includes(currentMember?.role)); return <div className="settlement-row" key={row.id}><span>{row.from_name} → {row.to_name}<small>{row.settlement_date} · {t(`settlements.status.${row.status}`)}</small></span><strong>{row.amount} {currency}</strong>{canReview && <div className="row-actions"><button onClick={() => onReview(row, 'confirm')}>{t('settlements.confirm')}</button><button onClick={() => onReview(row, 'reject')}>{t('settlements.reject')}</button></div>}{manageable && row.status !== 'pending' && <div className="row-actions"><button onClick={() => edit(row)}>{t('common.edit')}</button><button onClick={() => onDelete(row)}>{t('common.delete')}</button></div>}</div>; }) : <p>{t('settlements.empty')}</p>}
  </section>;
};

export default SettlementsPanel;
