import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

const SettlementsPanel = ({ members, currency, settlements, suggestion, currentMember, onSave, onDelete, disabled }) => {
  const { t } = useTranslation();
  const [form, setForm] = useState({ from_member_id: suggestion?.from_member || currentMember?.id || '', to_member_id: suggestion?.to_member || '', amount: suggestion?.amount || '', settlement_date: new Date().toISOString().slice(0, 10), note: '' });
  const submit = (e) => { e.preventDefault(); onSave({ ...form, currency, idempotency_key: crypto.randomUUID() }); };
  return <section className="card-pc"><h2>{t('settlements.title')}</h2>{!disabled && <form onSubmit={submit}><label>{t('settlements.from')}<select className="pc-input" value={form.from_member_id} onChange={(e) => setForm({ ...form, from_member_id: e.target.value })}>{members.map((m) => <option key={m.id} value={m.id}>{m.display_name}</option>)}</select></label><label>{t('settlements.to')}<select className="pc-input" value={form.to_member_id} onChange={(e) => setForm({ ...form, to_member_id: e.target.value })}><option value="">—</option>{members.map((m) => <option key={m.id} value={m.id}>{m.display_name}</option>)}</select></label><label>{t('expense.amount')}<input className="pc-input" type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>{t('expense.date')}<input className="pc-input" type="date" value={form.settlement_date} onChange={(e) => setForm({ ...form, settlement_date: e.target.value })} /></label><label>{t('expense.notes')}<input className="pc-input" value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><button className="pc-btn-create" disabled={!form.to_member_id || form.from_member_id === form.to_member_id}>{t('settlements.record')}</button></form>}<h3>{t('settlements.history')}</h3>{settlements.length ? settlements.map((row) => <div className="settlement-row" key={row.id}><span>{row.from_name} → {row.to_name}<small>{row.settlement_date}</small></span><strong>{row.amount} {currency}</strong>{!disabled && (currentMember?.role !== 'member' || row.created_by === currentMember?.id) && <button onClick={() => onDelete(row)}>{t('common.delete')}</button>}</div>) : <p>{t('settlements.empty')}</p>}</section>;
};
export default SettlementsPanel;
