import axios from 'axios';

const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:8000/api/v1';
const api = axios.create({ baseURL: API_BASE_URL, withCredentials: true, timeout: 15000 });
api.interceptors.request.use((config) => {
  const csrf = document.cookie.split('; ').find((row) => row.startsWith('csrftoken='))?.split('=')[1];
  if (csrf) config.headers['X-CSRFToken'] = decodeURIComponent(csrf);
  return config;
});
const data = (request) => request.then((response) => response.data);
const guestKey = (tripId) => `tripsplit:guest:${tripId}`;
export const saveGuestToken = (tripId, token) => localStorage.setItem(guestKey(tripId), token);
export const getGuestToken = (tripId) => localStorage.getItem(guestKey(tripId));
const guestConfig = (tripId) => ({ headers: getGuestToken(tripId) ? { 'X-Guest-Token': getGuestToken(tripId) } : {} });

export const requestOtp = (email) => data(api.post('/auth/otp/request/', { email }));
export const verifyOtp = (payload) => data(api.post('/auth/otp/verify/', payload));
export const getCurrentUser = () => data(api.get('/auth/me/'));
export const logout = () => data(api.post('/auth/logout/'));
export const updateProfile = (payload) => data(api.patch('/profile/', payload));
export const requestEmailChange = (email) => data(api.post('/profile/email/change/request/', { email }));
export const verifyEmailChange = (payload) => data(api.post('/profile/email/change/verify/', payload));
export const createTrip = async (payload) => { const response = await data(api.post('/trips/', payload)); if (response.guest_token) saveGuestToken(response.trip.id, response.guest_token); return response; };
export const joinTrip = async (payload) => { const response = await data(api.post('/trips/join/', payload)); if (response.guest_token && response.trip) saveGuestToken(response.trip.id, response.guest_token); return response; };
export const getTrips = () => data(api.get('/trips/'));
export const getTrip = (tripId) => data(api.get(`/trips/${tripId}/`, guestConfig(tripId)));
export const getMembers = (tripId) => data(api.get(`/trips/${tripId}/members/`, guestConfig(tripId)));
export const getExpenses = (tripId) => data(api.get(`/trips/${tripId}/expenses/`, guestConfig(tripId)));
export const getPage = (url, tripId) => data(api.get(url, guestConfig(tripId)));
export const addExpense = (tripId, payload) => data(api.post(`/trips/${tripId}/expenses/`, payload, guestConfig(tripId)));
export const updateExpense = (tripId, expenseId, payload) => data(api.patch(`/trips/${tripId}/expenses/${expenseId}/`, payload, guestConfig(tripId)));
export const deleteExpense = (tripId, expenseId) => data(api.delete(`/trips/${tripId}/expenses/${expenseId}/`, guestConfig(tripId)));
export const getCategoryBudgets = (tripId) => data(api.get(`/trips/${tripId}/category-budgets/`, guestConfig(tripId)));
export const getBalances = (tripId) => data(api.get(`/trips/${tripId}/balances/`, guestConfig(tripId)));
export const getSettlements = (tripId) => data(api.get(`/trips/${tripId}/settlements/`, guestConfig(tripId)));
export const addSettlement = (tripId, payload) => data(api.post(`/trips/${tripId}/settlements/`, payload, guestConfig(tripId)));
export const updateSettlement = (tripId, settlementId, payload) => data(api.patch(`/trips/${tripId}/settlements/${settlementId}/`, payload, guestConfig(tripId)));
export const deleteSettlement = (tripId, settlementId) => data(api.delete(`/trips/${tripId}/settlements/${settlementId}/`, guestConfig(tripId)));
export const getActivity = (tripId) => data(api.get(`/trips/${tripId}/activity/`, guestConfig(tripId)));
export const updateTrip = (tripId, payload) => data(api.patch(`/trips/${tripId}/`, payload, guestConfig(tripId)));
export const archiveTrip = (tripId) => data(api.delete(`/trips/${tripId}/`, guestConfig(tripId)));
export const restoreTrip = (tripId) => data(api.post(`/trips/${tripId}/restore/`, {}, guestConfig(tripId)));
export const updateMember = (tripId, memberId, payload) => data(api.patch(`/trips/${tripId}/members/${memberId}/`, payload, guestConfig(tripId)));
export const removeMember = (tripId, memberId) => data(api.delete(`/trips/${tripId}/members/${memberId}/`, guestConfig(tripId)));
export const transferOwnership = (tripId, memberId) => data(api.post(`/trips/${tripId}/transfer-ownership/`, { member_id: memberId }, guestConfig(tripId)));
export const leaveTrip = (tripId) => data(api.post(`/trips/${tripId}/leave/`, {}, guestConfig(tripId)));
export const getJoinRequests = (tripId) => data(api.get(`/trips/${tripId}/join-requests/`, guestConfig(tripId)));
export const reviewJoinRequest = (tripId, requestId, decision, reason = '') => data(api.post(`/trips/${tripId}/join-requests/${requestId}/${decision}/`, { reason }, guestConfig(tripId)));
export const getJoinRequestStatus = async (requestId, requestToken) => { const response = await data(api.get(`/join-requests/${requestId}/`, { headers: requestToken ? { 'X-Join-Request-Token': requestToken } : {} })); if (response.guest_token && response.trip?.public_id) saveGuestToken(response.trip.public_id, response.guest_token); return response; };
export const cancelJoinRequest = (requestId, requestToken) => data(api.delete(`/join-requests/${requestId}/`, { headers: requestToken ? { 'X-Join-Request-Token': requestToken } : {} }));
export const getBans = (tripId) => data(api.get(`/trips/${tripId}/bans/`, guestConfig(tripId)));
export const kickMember = (tripId, memberId) => data(api.post(`/trips/${tripId}/members/${memberId}/kick/`, {}, guestConfig(tripId)));
export const banMember = (tripId, memberId, payload) => data(api.post(`/trips/${tripId}/members/${memberId}/ban/`, payload, guestConfig(tripId)));
export const revokeBan = (tripId, banId) => data(api.post(`/trips/${tripId}/bans/${banId}/revoke/`, {}, guestConfig(tripId)));
export const getInvitations = (tripId) => data(api.get(`/trips/${tripId}/invitations/`, guestConfig(tripId)));
export const createInvitation = (tripId, payload) => data(api.post(`/trips/${tripId}/invitations/`, payload, guestConfig(tripId)));
export const revokeInvitation = (tripId, invitationId) => data(api.post(`/trips/${tripId}/invitations/${invitationId}/revoke/`, {}, guestConfig(tripId)));
export const resendInvitation = (tripId, invitationId) => data(api.post(`/trips/${tripId}/invitations/${invitationId}/resend/`, {}, guestConfig(tripId)));
export const getInvitation = (token) => data(api.get(`/invitations/${token}/`));
export const acceptInvitation = async (token, payload) => { const response = await data(api.post(`/invitations/${token}/`, payload)); if (response.guest_token) saveGuestToken(response.trip.id, response.guest_token); return response; };
export const getCategories = (tripId) => data(api.get(`/trips/${tripId}/categories/`, guestConfig(tripId)));
export const createCategory = (tripId, payload) => data(api.post(`/trips/${tripId}/categories/`, payload, guestConfig(tripId)));
export const updateCategory = (tripId, categoryId, payload) => data(api.patch(`/trips/${tripId}/categories/${categoryId}/`, payload, guestConfig(tripId)));
export const archiveCategory = (tripId, categoryId) => data(api.delete(`/trips/${tripId}/categories/${categoryId}/`, guestConfig(tripId)));
export const setCategoryBudget = (tripId, payload) => data(api.post(`/trips/${tripId}/category-budgets/`, payload, guestConfig(tripId)));
export const resetCategoryBudget = (tripId, categoryId) => data(api.delete(`/trips/${tripId}/category-budgets/${categoryId}/`, guestConfig(tripId)));
export const getMemberDetail = (tripId, memberId) => data(api.get(`/trips/${tripId}/members/${memberId}/`, guestConfig(tripId)));
export const getTripSummary = (tripId) => data(api.get(`/trips/${tripId}/summary/`, guestConfig(tripId)));
export const reviewSettlement = (tripId, settlementId, decision) => data(api.post(`/trips/${tripId}/settlements/${settlementId}/${decision}/`, {}, guestConfig(tripId)));
export const closeTrip = (tripId) => data(api.post(`/trips/${tripId}/close/`, {}, guestConfig(tripId)));
export const reopenTrip = (tripId) => data(api.post(`/trips/${tripId}/reopen/`, {}, guestConfig(tripId)));
export const getFund = (tripId) => data(api.get(`/trips/${tripId}/fund/`, guestConfig(tripId)));
export const createFund = (tripId, payload) => data(api.post(`/trips/${tripId}/fund/`, payload, guestConfig(tripId)));
export const updateFund = (tripId, payload) => data(api.patch(`/trips/${tripId}/fund/`, payload, guestConfig(tripId)));
export const createFundingRound = (tripId, payload) => data(api.post(`/trips/${tripId}/fund/rounds/`, payload, guestConfig(tripId)));
export const recordFundContribution = (tripId, roundId, payload) => data(api.post(`/trips/${tripId}/fund/rounds/${roundId}/contributions/`, payload, guestConfig(tripId)));
export const previewFundRefund = (tripId, payload) => data(api.post(`/trips/${tripId}/fund/refund-preview/`, payload, guestConfig(tripId)));
export const recordFundRefunds = (tripId, payload) => data(api.post(`/trips/${tripId}/fund/refunds/`, payload, guestConfig(tripId)));
export const closeFund = (tripId) => data(api.post(`/trips/${tripId}/fund/close/`, {}, guestConfig(tripId)));
export default api;
