import React,{useState}from'react';import{useTranslation}from'react-i18next';import Avatar from'../../profile/components/Avatar';import{avatarKeyFromAvatar}from'../../profile/utils/avatarKey';
// Fund contribution reminder -- a distinct domain/event/template from the
// Balances personal-debt reminder (see docs/architecture/notifications.md);
// never presented as the same kind of notification. Kept minimal and
// styled with this file's own existing legacy classes (bare <button>,
// .fund-member-remind) rather than importing the Neo-classic balances.css
// into a page that doesn't otherwise use that system -- this is the one
// small, explicitly-scoped Fund touchpoint for this task, not a redesign.
export default function FundingRoundCard({round,currency,canManage,onComplete,onCancel,onRemind}){const{t}=useTranslation(),s=round.statistics;const[reminderStates,setReminderStates]=useState({});const remind=async(memberId,displayName)=>{setReminderStates(current=>({...current,[memberId]:{status:'sending'}}));try{await onRemind(memberId);setReminderStates(current=>({...current,[memberId]:{status:'sent',displayName}}));window.setTimeout(()=>setReminderStates(current=>({...current,[memberId]:null})),6000)}catch(error){const status=error?.code==='reminder_cooldown'?'cooldown':'error';setReminderStates(current=>({...current,[memberId]:{status}}));window.setTimeout(()=>setReminderStates(current=>({...current,[memberId]:null})),6000)}};return<article className="fund-round"><header><h3>#{round.sequence_number} {round.title}</h3><strong>{t(`fund.status.${round.status}`)}</strong></header><p>{t('fund.target')} {s.target} · {t('fund.collected')} {s.collected} · {t('fund.remaining')} {s.remaining} {currency}</p><progress max="100" value={Math.min(Number(s.percentage_collected),100)}/>{s.members.map(row=>{const owesMore=Number(row.remaining)>0;const state=reminderStates[row.member_id];return<div className="fund-member" key={row.member_id}><span><Avatar avatarKey={avatarKeyFromAvatar(row.avatar)} displayName={row.display_name} size="sm" /> {row.display_name}</span><span>{t('fund.expected')} {row.expected} · {t('fund.paid')} {row.paid} · {t('fund.remaining')} {row.remaining}{Number(row.overpaid)>0?` · ${t('fund.overpaid')} ${row.overpaid}`:''}</span>{canManage&&round.status==='open'&&owesMore&&onRemind&&<span className="fund-member-remind"><button type="button" disabled={state?.status==='sending'} aria-label={t('fund.remind')} title={t('fund.remind')} onClick={()=>remind(row.member_id,row.display_name)}><i className="bi bi-bell" aria-hidden="true"/> {t('fund.remind')}</button>{state&&state.status!=='sending'&&<small role="status" aria-live="polite">{state.status==='sent'&&t('fund.reminderSent',{name:state.displayName})}{state.status==='cooldown'&&t('fund.reminderCooldown')}{state.status==='error'&&t('error.action')}</small>}</span>}</div>})}{canManage&&round.status==='open'&&<div className="fund-actions"><button type="button" onClick={()=>onComplete(round,Number(s.remaining))}>{t('fund.completeRound')}</button><button type="button" disabled={Number(s.collected)>0} onClick={()=>onCancel(round)}>{t('fund.cancelRound')}</button></div>}</article>}
