import React,{useMemo,useState}from'react';
import{useTranslation}from'react-i18next';
import RefundPreview from'./RefundPreview';
const today=()=>new Date().toISOString().slice(0,10);
export default function RefundPanel({surplus,rounds,currency,onPreview,onRefund}){
 const{t}=useTranslation(),[form,setForm]=useState({method:'proportional_to_net_contributions',distribution_amount:'',custom:{}}),[preview,setPreview]=useState(null);
 const members=useMemo(()=>(rounds||[]).flatMap(r=>r.statistics.members).filter((r,i,a)=>a.findIndex(x=>x.member_id===r.member_id)===i),[rounds]);
 const amount=Number(form.distribution_amount||surplus),allocated=Object.values(form.custom).reduce((n,x)=>n+(Number(x)||0),0),remaining=amount-allocated;
 const payload=()=>({method:form.method,distribution_amount:form.distribution_amount||surplus,member_ids:form.method==='equal'?members.map(m=>m.member_id):undefined,custom:form.method==='custom'?Object.entries(form.custom).filter(([,v])=>Number(v)>0).map(([member_id,value])=>({member_id,amount:value})):undefined});
 if(Number(surplus)<=0)return null;
 return <div className="fund-form"><h3>{t('fund.refund')}</h3><p>{t('fund.available')}: {surplus} {currency}</p><label>{t('fund.distributionAmount')}<input aria-label={t('fund.distributionAmount')} inputMode="decimal" type="number" min="0.01" max={surplus} step="0.01" value={form.distribution_amount} placeholder={surplus} onChange={e=>{setForm({...form,distribution_amount:e.target.value});setPreview(null)}}/></label><select aria-label={t('fund.refundMethod')} className="pc-input" value={form.method} onChange={e=>{setForm({...form,method:e.target.value});setPreview(null)}}><option value="proportional_to_net_contributions">{t('fund.proportional')}</option><option value="equal">{t('fund.equal')}</option><option value="custom">{t('fund.custom')}</option><option value="keep_in_fund">{t('fund.keep')}</option></select>{form.method==='custom'&&<>{members.map(m=><label className="fund-custom-refund" key={m.member_id}>{m.display_name}<input aria-label={`${m.display_name} ${t('fund.refund')}`} inputMode="decimal" type="number" min="0" step="0.01" value={form.custom[m.member_id]||''} onChange={e=>{setForm({...form,custom:{...form.custom,[m.member_id]:e.target.value}});setPreview(null)}}/></label>)}<p>{t('fund.allocated')}: {allocated.toFixed(2)} {currency} · {t('fund.unallocated')}: {remaining.toFixed(2)} {currency}</p></>}{form.method!=='keep_in_fund'?<button type="button" disabled={form.method==='custom'&&(allocated<=0||Math.abs(remaining)>.0001)} onClick={async()=>setPreview(await onPreview(payload()))}>{t('fund.preview')}</button>:<p>{t('fund.keepExplanation')}</p>}{preview&&<RefundPreview preview={preview} currency={currency} onConfirm={()=>onRefund({...payload(),distribution_amount:preview.distribution_amount,refund_date:today(),idempotency_key:crypto.randomUUID()})}/>}</div>
}
